#!/bin/sh

# SHELL=/bin/sh script --flush --quiet --return /var/tmp/workbench --command "@app_id@ $@"
SHELL=/bin/sh script --flush --quiet --return /var/tmp/workbench --command "G_MESSAGES_DEBUG=\"all\" @app_id@ $@"
