name: CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # See also https://github.com/flatpak/flatpak-github-actions
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: flatpak flatpak-builder mutter
          version: 1.0

      - name: Cache Flatpak dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/flatpak
          key: ${{ runner.os }}-dependencies

      - name: Cache flatpa-builder
        uses: actions/cache@v3
        with:
          path: .flatpak-builder
          key: ${{ runner.os }}-flatpak-builder

      - run: nohup mutter --wayland --headless --virtual-monitor 1280x720 &
      - run: export WAYLAND_DISPLAY=wayland-1 && && make ci
