name: CI

# See also https://github.com/flatpak/flatpak-github-actions

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-26.04

    steps:
      # Cache apt
      - name: Cache apt
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: apt-cache-${{ runner.arch }}

      # Cache Flatpak
      - name: Cache Flatpak dependencies
        uses: actions/cache@v4
        with:
          path: ~/.local/share/flatpak
          key: flatpak-deps-${{ runner.arch }}

      # Cache flatpak-builder state
      - name: Cache .flatpak-builder
        uses: actions/cache@v4
        with:
          path: .flatpak-builder
          key: flatpak-builder-${{ runner.arch }}

      # Cache Foundry
      - name: Cache .foundry
        uses: actions/cache@v4
        with:
          path: .foundry
          key: foundry-${{ runner.arch }}

      - name: Install host dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install flatpak mutter flatpak-builder foundry

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: "npm"

      - run: mutter --wayland --no-x11 --headless --wayland-display=wayland-0 --virtual-monitor 1280x720 > /tmp/mutter.log 2>&1 &
      - run: make FLATPAK_ARGS=--user ci
      - run: cat /tmp/mutter.log
