name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        name: "Build"
        with:
          bundle: re.sonny.Workbench.Devel.flatpak
          manifest-path: build-aux/re.sonny.Workbench.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}

      - uses: flatpak/flatpak-github-actions/flat-manager@v6
        name: "Deploy"
        with:
          repository: nightly
          flat-manager-url: https://flat-manager.gnome.org/
          token: ${{ secrets.GNOME_NIGHTLY_TOKEN }}
